name: secret_gallery
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.3

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.0
  path: ^1.9.0
  sqflite: ^2.3.3
  image_picker: ^1.1.2
  shared_preferences: ^2.3.0
  share_plus: ^10.1.4
  permission_handler: ^11.3.0
  photo_manager: ^3.0.0
  flutter_reorderable_grid_view: ^5.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
